#!/bin/bash

#### Settings ####

COMPUTER_NAME="MeKyle-osx"
DOT_FILES="
.aws
.bash_itrc
.bash_profile
.bashrc
.gitconfig
.gitignore.profiles.js
.inputrc
.npmrc
.ssh
"

BREW_PROGRAMS="
git
hugo
jq
mas
node
openssl
rbenv
ruby-build
ssh-copy-id
"

CASK_PROGRAMS="
1password
adobe-creative-cloud
aerial
alfred
atom
avast-secureline-vpn
bartender
blisk
caffeine
cleanmymac
dropbox
evernote
google-chrome
google-photos-backup-and-sync
grammarly
imageoptim
krisp
music-manager
muzzle
numi
rescuetime
sketch
skype
spectacle
the-unarchiver
whatsapp
"

APP_STORE_PROGRAMS="
Clean
Contrast
Spark
Todoist
Xcode
"

NPM_MODULES="
@vue/cli
gitignorer
outdated
serverless
standard
"

APM_MODULES="
emmet
language-gherkin
language-graphql
language-hugo
language-markdown
language-vue
linter
linter-js-standard
linter-ui-default
pigments
sort-lines
standard-formatter
"

BASH_IT_ALIAS="
bundler
general
git
osx
"

BASH_IT_COMPLETIONS="
bash-it
brew
brew
git
npm
rake
ssh
system
"

BASH_IT_PLUGINS="
extract
alias-completion
ruby
xterm
rbenv
"

#### Settings End #####


RED='\033[0;31m'
NC='\033[0m' # No Color
SCRIPT_PATH="`dirname \"$0\"`"

# Abort on error
set -e
source ./lib/heleprs.bash

# Check for git
git_command=`find_command git`
# Check for curl
curl_command=`find_command curl`
# Check for ruby
ruby_command=`find_command ruby`

source ./lib/bash-it.bash

source ./lib/brew.bash
source ./lib/brew-cask.bash

source ./lib/npm.bash
source ./lib/apm.bash

source ./lib/mac-app-store.bash

for filename in $DOT_FILES; do
  echo "# Copying ${filename}"
  from_file="${SCRIPT_PATH}/${filename}"
  to_file="${HOME}/${filename}"
  copy_file="cp -a ${from_file} ${to_file}"
  backup_file="cp -a ${to_file} ${to_file}.backup"
  if [ -e "${to_file}" ]; then
    run "$backup_file"
  fi
  run "$copy_file"
done

Set ~/.ssh/config to 600

# run ".macos"


# cleaning up
echo -e "\n${RED}Please relogin to see changes.${NC}"
