name: Test

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: ./setup.sh | grep "Kyle Welsby's dotfiles Installed"