name: Test

on: push

jobs:
  build:
    name: Test
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: ./install.sh --no-app-store --no-projects --no-bash-it